### ISSUE TITLE
sta

### ISSUE THREAD

**Issue by ungentilgarcon** [clemsos/bandstour#2]

**Comment by clemsos** [comment]
???

**Comment by ungentilgarcon** [comment]
ouai j me suis dit pas la peine de le marquer, je corrigerai ;) mais du coup ca a cree une issue vide 

----- Mail original -----

De: "Clément Renaud" notifications@github.com 
À: "clemsos/bandstour" bandstour@noreply.github.com 
Cc: "ungentilgarcon" gregory.bahde@laposte.net 
Envoyé: Vendredi 18 Septembre 2015 08:40:34 
Objet: Re: [bandstour] sta (#2) 

???
